// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hla_sort
std::vector<std::string> hla_sort(std::vector<std::string> alleles);
RcppExport SEXP HLAsim_hla_sort(SEXP allelesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type alleles(allelesSEXP);
    __result = Rcpp::wrap(hla_sort(alleles));
    return __result;
END_RCPP
}
// field1
std::vector<std::string> field1(std::vector<std::string> a);
RcppExport SEXP HLAsim_field1(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type a(aSEXP);
    __result = Rcpp::wrap(field1(a));
    return __result;
END_RCPP
}
// field2
std::vector<std::string> field2(std::vector<std::string> a);
RcppExport SEXP HLAsim_field2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type a(aSEXP);
    __result = Rcpp::wrap(field2(a));
    return __result;
END_RCPP
}
